name: employee_project
version: 1.0.0
config-version: 2

profile: employee_project

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  employee_project:
    staging:
      +schema: staging
      +materialized: view
      +persist_docs:
        relation: true
        columns: true
    core:
      +schema: core
      +materialized: table
      +persist_docs:
        relation: true
        columns: true
    marts:
      +schema: marts
      +materialized: table
      +persist_docs:
        relation: true
        columns: true
